### ISSUE TITLE
Tracking issue for v2022.10.18+

### ISSUE THREAD

**Issue by Galster-dev** [CrowdedMods/CrowdedMod#48]
Tracking issue to add support for v2022.10.18 and(or) v2022.10.25

TODO
- [x] Wait for updates to release on other platforms (Steam only for now)
- [x] Wait for [Reactor](https://github.com/NuclearPowered/Reactor) stable release
- [x] Research and fix impostor limit savefile clamping (`SaveManager` is reworked in latest)
- [x] Research any other breaking changes
- [x] Tests
- [x] Stabilize CoreCLR build and stop serving other versions due to [Reactor](https://github.com/NuclearPowered/Reactor) and [BepInEx](https://github.com/BepInEx/BepInEx) updates
